name: easy_form_builder
description: "Flutter easy form builder allow user to create form easily. Follow example to understand features"
version: 1.0.6
homepage: https://github.com/mynumeric-mobile/easy_form_builder

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_gradient_selector: ^1.0.12
  dynamic_fonts: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
 

    