name: flutter_dynamic_form
description: "Flutter Dynamic Form allow user to create form easily."
version: 0.0.1
homepage: https://github.com/mynumeric-mobile/flutter_dynamic_form

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  web:

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_gradient_selector: ^1.0.12
  dynamic_fonts: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
 

    